## This file is automatically generated
## Standard maketest.g for the homalg project

LoadPackage( "VirtualCAS" );
LoadPackage( "IO_ForHomalg" );
HOMALG_IO.show_banners := false;
HOMALG_IO.suppress_PID := true;
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "VirtualCAS", "doc" )[1]![1], "VirtualCAS.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "VirtualCAS" );
QUIT;
